### ISSUE TITLE
error: expected identifier EV_ERROR ev.h

### ISSUE THREAD

**Issue by tgy** [redis/hiredis#602]
I'm trying to compile a program that uses [redox](https://github.com/hmartiro/redox), which itself uses `hiredis`.

When trying to compile I get the following error

```
In file included from /Users/me/project/thirdparty/redox/include/redox/client.hpp:39:
In file included from /usr/local/include/hiredis/adapters/libev.h:35:
/usr/local/include/ev.h:240:3: error: expected identifier
  EV_ERROR    = (int)0x80000000  /* sent when an error occurs */
  ^
/usr/include/sys/event.h:170:29: note: expanded from macro 'EV_ERROR'
#define EV_ERROR            0x4000              /* error, data contains errno */
```

This error seems to have been mentioned only **once** on the Internet, on [this mailing list](https://www.mail-archive.com/libev@lists.schmorp.de/msg02654.html).

I'm not sure about what I should do to fix this issue here, so if someone can help it'd be great!

My version of `hiredis`:

```
valoup:build viovene$ brew info hiredis
hiredis: stable 0.13.3 (bottled), HEAD
Minimalistic client for Redis
https://github.com/redis/hiredis
/usr/local/Cellar/hiredis/0.13.3 (31 files, 189.4KB) *
  Poured from bottle on 2018-07-06 at 23:16:01
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hiredis.rb
==> Options
--HEAD
        Install HEAD version
```

**Comment by michael-grunder** [comment]
Hi!

So I did a bit of searching and it looks like this is a known bug in libev:
[Related bug in another project](https://github.com/cocaine/cocaine-framework-native/issues/8#issuecomment-37831669)
[Relevant bug on SO](https://stackoverflow.com/questions/16660816/libev-4-15-doesnt-compile-on-osx-10-8)

Interestingly I do not see this behavior unless I really force it by doing something like this:

```C++
#include <iostream>
#include <sys/event.h>

#include <ev++.h>

int main(void) {
    std::cout << EV_ERROR << std::endl;
}
```

Which illustrates the issue:

```bash
/usr/local/include/ev.h:240:3: error: expected identifier
  EV_ERROR    = (int)0x80000000  /* sent when an error occurs */
  ^
/usr/include/sys/event.h:170:29: note: expanded from macro 'EV_ERROR'
#define EV_ERROR            0x4000              /* error, data contains errno */
```

What the cocaine project (amazing name) folks did was apply an ifdef fix which was something like this [link](https://github.com/cocaine/cocaine-framework-native/commit/29a6c5ecb9a394a334eaf1aad316899f0c8e4245#diff-c346bf41ab21764782651032d866f6a7R29):

```C++
#ifdef __APPLE__
#ifdef EV_ERROR
#undef EV_ERROR
#endif
#endif
```

That sort of fix should solve the problem, but I don't know enough about the OSX internals to know if this is unsafe for some reason.

You may be able to solve your problem with a strategic use of the above `#ifdef`.  You want it after the OSX file gets included but before libev.

**Comment by tgy** [comment]
Hi Michael! Thanks for taking the time to look this up and write this detailed reply.

I'm not including the `ev++.h` header myself, it's rather included by `redox.hpp`.

Here's the beginning of the include section of my program's entry point:

```cpp
#ifdef __APPLE__
#ifdef EV_ERROR
#undef EV_ERROR
#endif
#endif

#include <iostream>
#include <thread>
#include <csignal>
#include <ctime>
#include <fstream>

#include <boost/asio.hpp>
#include <redox.hpp>
#include <gflags/gflags.h>
```

Sadly, the work-around you provided did not work for me. I still get the error

```
In file included from /Users/me/project/thirdparty/redox/include/redox.hpp:23:
In file included from /Users/me/project/thirdparty/redox/include/redox/client.hpp:39:
In file included from /usr/local/include/hiredis/adapters/libev.h:35:
/usr/local/include/ev.h:240:3: error: expected identifier
  EV_ERROR    = (int)0x80000000  /* sent when an error occurs */
  ^
/usr/include/sys/event.h:170:29: note: expanded from macro 'EV_ERROR'
#define EV_ERROR            0x4000              /* error, data contains errno */
                            ^
```

**Comment by tgy** [comment]
Ok, I just understood that I had to put it after the `<boost/asio.hpp>` include. That's the one that was probably conflicting.

```cpp
#include <iostream>
#include <thread>
#include <csignal>
#include <ctime>
#include <fstream>

#include <boost/asio.hpp>
#ifdef __APPLE__
#ifdef EV_ERROR
#undef EV_ERROR
#endif
#endif
#include <redox.hpp>
#include <gflags/gflags.h>
```

This compiles.

**Comment by michael-grunder** [comment]
I'm glad you got it working!  I'm going to close the issue here since I don't think we'd want to automatically add this `#undef` unless we start getting more reports of it causing people issues.

At least now when anyone runs into this issue they should come across this thread. 😊
